### ISSUE TITLE
catkin tools extension doesn't load anymore (maybe after vscode version update to 1.77.0)

### ISSUE THREAD

**Issue by rsarrazin2** [betwo/vscode-catkin-tools#52]
Until recently (hard to reconstruct what has changed) the extension had worked flawlessly. Now the extension host outputs (and the extension doesn't work anymore):
```
2023-04-04 18:57:57.226 [error] Activating extension betwo.b2-catkin-tools failed due to an error:
2023-04-04 18:57:57.226 [error] TypeError: Cannot redefine property: prepareStackTrace
	at Function.defineProperty (<anonymous>)
	at Module.1015 (/home/vscode/.vscode-server/extensions/betwo.b2-catkin-tools-4.7.0/dist/extension.js:2:269093)
	at n (/home/vscode/.vscode-server/extensions/betwo.b2-catkin-tools-4.7.0/dist/extension.js:2:287490)
	at Object.8698 (/home/vscode/.vscode-server/extensions/betwo.b2-catkin-tools-4.7.0/dist/extension.js:2:172574)
	at n (/home/vscode/.vscode-server/extensions/betwo.b2-catkin-tools-4.7.0/dist/extension.js:2:287490)
	at Object.7260 (/home/vscode/.vscode-server/extensions/betwo.b2-catkin-tools-4.7.0/dist/extension.js:2:182116)
	at n (/home/vscode/.vscode-server/extensions/betwo.b2-catkin-tools-4.7.0/dist/extension.js:2:287490)
	at Object.2128 (/home/vscode/.vscode-server/extensions/betwo.b2-catkin-tools-4.7.0/dist/extension.js:2:144357)
	at n (/home/vscode/.vscode-server/extensions/betwo.b2-catkin-tools-4.7.0/dist/extension.js:2:287490)
	at Object.1725 (/home/vscode/.vscode-server/extensions/betwo.b2-catkin-tools-4.7.0/dist/extension.js:2:145227)
	at n (/home/vscode/.vscode-server/extensions/betwo.b2-catkin-tools-4.7.0/dist/extension.js:2:287490)
	at Object.8872 (/home/vscode/.vscode-server/extensions/betwo.b2-catkin-tools-4.7.0/dist/extension.js:2:156020)
	at n (/home/vscode/.vscode-server/extensions/betwo.b2-catkin-tools-4.7.0/dist/extension.js:2:287490)
	at Object.112 (/home/vscode/.vscode-server/extensions/betwo.b2-catkin-tools-4.7.0/dist/extension.js:2:255108)
	at n (/home/vscode/.vscode-server/extensions/betwo.b2-catkin-tools-4.7.0/dist/extension.js:2:287490)
	at /home/vscode/.vscode-server/extensions/betwo.b2-catkin-tools-4.7.0/dist/extension.js:2:287921
	at Object.<anonymous> (/home/vscode/.vscode-server/extensions/betwo.b2-catkin-tools-4.7.0/dist/extension.js:2:287946)
	at Module._compile (node:internal/modules/cjs/loader:1103:14)
	at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
	at Module.load (node:internal/modules/cjs/loader:981:32)
	at Function.Module._load (node:internal/modules/cjs/loader:822:12)
	at Function.m._load (/vscode/vscode-server/bin/linux-x64/7f329fe6c66b0f86ae1574c2911b681ad5a45d63/out/vs/workbench/api/node/extensionHostProcess.js:125:14199)
	at Function.h._load (/vscode/vscode-server/bin/linux-x64/7f329fe6c66b0f86ae1574c2911b681ad5a45d63/out/vs/workbench/api/node/extensionHostProcess.js:120:11871)
	at Function.C._load (/vscode/vscode-server/bin/linux-x64/7f329fe6c66b0f86ae1574c2911b681ad5a45d63/out/vs/workbench/api/node/extensionHostProcess.js:120:11264)
	at Module.require (node:internal/modules/cjs/loader:1005:19)
	at require (node:internal/modules/cjs/helpers:102:18)
	at Function.i [as __$__nodeRequire] (/vscode/vscode-server/bin/linux-x64/7f329fe6c66b0f86ae1574c2911b681ad5a45d63/out/vs/loader.js:5:98)
	at E.rb (/vscode/vscode-server/bin/linux-x64/7f329fe6c66b0f86ae1574c2911b681ad5a45d63/out/vs/workbench/api/node/extensionHostProcess.js:120:13135)
	at async Promise.all (index 0)
```

My setup: extension runs in a devcontainer running natively on Ubuntu 20.04 running on WSL2.

The only thing I did lately was to play with newer version of the ROS extension in the context of [this issue](https://github.com/ms-iot/vscode-ros/issues/910). But reverting to the version 0.8.4 of the latter doesn't solve the issue.

I'm afraid the log doesn't help. In that case, please tell me what I can try / enable to help analyzing the root cause.

Note the vscode version that has actually changed recently:
```
Version: 1.77.0 (user setup)
Commit: 7f329fe6c66b0f86ae1574c2911b681ad5a45d63
Date: 2023-03-29T10:02:16.981Z (6 days ago)
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: Yes
```

**Comment by rsarrazin2** [comment]
The problem is still present with today's version 1.77.1:
```
Version: 1.77.1 (user setup)
Commit: b7886d7461186a5eac768481578c1d7ca80e2d21
Date: 2023-04-04T23:21:11.906Z (1 day ago)
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: Yes
```

**Comment by Roboterbastler** [comment]
I can confirm the same issue, also version 1.77.1 of vscode and 4.7.0 of this plugin:

```
Version: 1.77.1
Commit: b7886d7461186a5eac768481578c1d7ca80e2d21
Date: 2023-04-04T23:20:37.202Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Linux x64 5.15.0-67-generic snap
Sandboxed: No
```

**Comment by betwo** [comment]
Thank you for reporting this, I can reproduce it.

**Comment by betwo** [comment]
From what I can tell, the latest code API and tslog 3.3.x have a naming collision resulting in this crash.
Updated both for version 4.7.1. and now I can't reproduce the problem anymore.

Please let me know if this still persists for you with 4.7.1!

**Comment by rsarrazin2** [comment]
Thank you for the quick fix. A first test confirms the functionality was restored with 4.7.1.
